package usage

import (
	"encoding/json"
	"fmt"
	"time"
)

// BundledCatalogVersionPrefix is the human-readable half of the generated
// bundled catalog's version string; BundledCatalogVersionFor appends the
// content digest. It replaces the hand-written, self-misdescribing
// "2026-07-13-openai-standard-v1" (which carried an Anthropic model).
const BundledCatalogVersionPrefix = "bundled-litellm-merged"

// BundledCatalogEffectiveFrom is the effective date stamped on every generated
// bundled model, and it is deliberately NOT the generation time.
//
// The bundled layer is the period-agnostic fallback of last resort: its job is
// to price usage when no fresher catalog exists, including usage that predates
// the build. priceAt gates each model on its own effective_from, so stamping
// generation time would leave every historical event unpriced on a fresh
// install — exactly the cold-start gap this catalog exists to close. It stays
// pinned to the date the bundled fallback layer was established so
// regeneration is idempotent and never silently re-dates existing prices; a
// fresher litellm or official catalog outranks it on catalog_effective
// regardless, so a stale bundled date can never beat real upstream data.
const BundledCatalogEffectiveFrom = "2026-07-13T00:00:00Z"

// bundledCatalogSource is this artifact's own provenance, the value
// ImportBundledCatalog records as source_url. It stays a single
// bundled:// sentinel entry: the catalog compiled into the binary is the
// source, and widening it would break the stable-provenance contract that
// price provenance reporting depends on.
type bundledCatalogSource struct {
	URL         string `json:"url"`
	RetrievedAt string `json:"retrieved_at"`
}

// bundledCatalogOrigin records what the artifact was generated *from*, which
// is deliberately separate from `sources` above: upstream identity is
// regeneration provenance, not this catalog's own identity.
// Deliberately carries no wall-clock timestamp: the pinned commit SHA
// identifies the upstream snapshot exactly, and a generation timestamp would
// make the artifact differ on every run, defeating the `genprices -check`
// reproducibility guard.
type bundledCatalogOrigin struct {
	URL       string `json:"url"`
	Kind      string `json:"kind"`
	CommitSHA string `json:"commit_sha,omitempty"`
	Note      string `json:"note,omitempty"`
}

type bundledCatalogDocument struct {
	SchemaVersion int                    `json:"schema_version"`
	Version       string                 `json:"catalog_version"`
	Currency      string                 `json:"currency"`
	Generated     string                 `json:"generated_note"`
	Sources       []bundledCatalogSource `json:"sources"`
	GeneratedFrom []bundledCatalogOrigin `json:"generated_from"`
	Models        map[string]modelPrice  `json:"models"`
}

const bundledCatalogGeneratedNote = "Generated by tools/genprices from a pinned LiteLLM commit, with internal/usage/price-gapfill.json merged over it. Do not hand-edit: run 'make prices-regen'. catalog_version carries a content digest, so any content change requires a regenerated version string (see VerifyBundledCatalogVersion)."

// RecordedLiteLLMCommit returns the pinned LiteLLM commit a generated bundled
// catalog records in its own `generated_from` metadata, so `genprices -check`
// can reproduce exactly the artifact that is committed rather than whatever
// LiteLLM main happens to be now. It fails loudly on missing, malformed, or
// ambiguous metadata instead of falling back to a different pin, because a
// silent fallback would make the reproducibility check compare against the
// wrong input and pass for the wrong reason.
func RecordedLiteLLMCommit(data []byte) (string, error) {
	var document struct {
		GeneratedFrom []struct {
			Kind      string `json:"kind"`
			CommitSHA string `json:"commit_sha"`
		} `json:"generated_from"`
	}
	if err := json.Unmarshal(data, &document); err != nil {
		return "", fmt.Errorf("read recorded LiteLLM commit: %w", err)
	}
	var found []string
	for _, origin := range document.GeneratedFrom {
		if origin.Kind == "litellm" {
			found = append(found, origin.CommitSHA)
		}
	}
	switch {
	case len(found) == 0:
		return "", fmt.Errorf("catalog records no litellm entry in generated_from; regenerate it with 'make prices-regen LITELLM_COMMIT=<sha>'")
	case len(found) > 1:
		return "", fmt.Errorf("catalog records %d litellm entries in generated_from, want exactly 1; its provenance is ambiguous", len(found))
	case !validLiteLLMCommit(found[0]):
		return "", fmt.Errorf("catalog records an invalid pinned LiteLLM commit %q", found[0])
	}
	return found[0], nil
}

// GenerateBundledCatalog builds the embedded bundled catalog from a pinned
// LiteLLM snapshot merged with the curated gap-fill, and stamps a
// content-derived version string.
//
// It reuses liteLLMCatalog, the same conversion the network `price update`
// path uses, so the bundled and litellm layers cannot disagree about how an
// upstream row becomes a price. Curated gap-fill entries are merged over the
// generated models (root cause 3: regeneration must never drop a model
// upstream does not price).
func GenerateBundledCatalog(liteLLMData []byte, commit string, gapfill Gapfill) ([]byte, error) {
	if !validLiteLLMCommit(commit) {
		return nil, fmt.Errorf("bundled catalog generation requires a pinned LiteLLM commit SHA, got %q", commit)
	}
	effectiveFrom, err := time.Parse(time.RFC3339Nano, BundledCatalogEffectiveFrom)
	if err != nil {
		return nil, err
	}
	// liteLLMCatalog stamps every model with the time it is handed, which is
	// correct for the network layer (you fetched it now) but wrong for a
	// bundled fallback (see BundledCatalogEffectiveFrom).
	generated, _, err := liteLLMCatalog(liteLLMData, commit, effectiveFrom)
	if err != nil {
		return nil, err
	}
	if err = validateGapfillEstimates(generated.Models, gapfill); err != nil {
		return nil, err
	}
	document := bundledCatalogDocument{
		SchemaVersion: 1,
		Currency:      "USD",
		Generated:     bundledCatalogGeneratedNote,
		Sources: []bundledCatalogSource{
			{URL: bundledCatalogSourceURL, RetrievedAt: BundledCatalogEffectiveFrom},
		},
		GeneratedFrom: []bundledCatalogOrigin{
			{
				URL:       liteLLMPriceURLPrefix + commit + liteLLMPriceURLSuffix,
				Kind:      "litellm",
				CommitSHA: commit,
				Note:      "Direct openai/anthropic records only; the chatgpt/ namespace carries no cost fields and is correctly excluded by the provider filter.",
			},
		},
		Models: MergeGapfill(generated.Models, gapfill),
	}
	if len(gapfill.Entries) > 0 {
		estimates := 0
		for _, entry := range gapfill.Entries {
			if entry.PriceKind() == GapfillKindEquivalentEstimate {
				estimates++
			}
		}
		note := fmt.Sprintf("%d curated price(s) for models upstream does not price; each carries its own verified source_url.", len(gapfill.Entries))
		if estimates > 0 {
			note += fmt.Sprintf(" %d of them are explicitly marked equivalent estimates that borrow a named vendor-priced basis model's rate; they are not published rates for the model itself and not a subscription invoice.", estimates)
		}
		document.GeneratedFrom = append(document.GeneratedFrom, bundledCatalogOrigin{
			URL:  "bundled://agentdeck/price-gapfill.json",
			Kind: "curated",
			Note: note,
		})
	}

	// Stamp the version from the finished contents, then re-marshal so the
	// emitted bytes carry it. The digest ignores catalog_version itself, so
	// this converges in one pass.
	document.Version = ""
	staged, err := json.Marshal(document)
	if err != nil {
		return nil, err
	}
	version, err := BundledCatalogVersionFor(staged, BundledCatalogVersionPrefix)
	if err != nil {
		return nil, err
	}
	document.Version = version

	encoded, err := json.MarshalIndent(document, "", "  ")
	if err != nil {
		return nil, err
	}
	encoded = append(encoded, '\n')
	if err = VerifyBundledCatalogVersion(encoded); err != nil {
		return nil, fmt.Errorf("generated catalog failed its own version guard: %w", err)
	}
	return encoded, nil
}
